import { boardLength } from "./game/constants";

export const doubleWord = [
  boardLength + 4,
  2 * boardLength - 5,
  4 * boardLength + 1,
  4 * boardLength + 9,
  5 * boardLength - 2,
  7 * boardLength + 7,
  8 * boardLength - 8,
  9 * boardLength + 4,
  10 * boardLength - 5,
  11 * boardLength + 7,
  12 * boardLength - 8,
  14 * boardLength + 1,
  14 * boardLength + 9,
  15 * boardLength - 2,
  17 * boardLength + 4,
  18 * boardLength - 5,
];
export const tripleWord = [
  0,
  7,
  boardLength - 8,
  boardLength - 1,
  3 * boardLength + 3,
  4 * boardLength - 4,
  5 * boardLength + 5,
  6 * boardLength - 6,
  7 * boardLength,
  8 * boardLength - 1,
  11 * boardLength,
  12 * boardLength - 1,
  13 * boardLength + 5,
  14 * boardLength - 6,
  15 * boardLength + 3,
  16 * boardLength - 4,
  18 * boardLength,
  18 * boardLength + 7,
  19 * boardLength - 8,
  19 * boardLength - 1,
];
export const doubleLetter = [
  boardLength + 2,
  2 * boardLength - 3,
  2 * boardLength + 1,
  2 * boardLength + 6,
  3 * boardLength - 7,
  3 * boardLength - 2,
  4 * boardLength + 8,
  5 * boardLength - 9,
  6 * boardLength + 2,
  7 * boardLength - 3,
  8 * boardLength + 4,
  8 * boardLength + 8,
  9 * boardLength - 5,
  9 * boardLength - 9,
  10 * boardLength + 4,
  10 * boardLength + 8,
  11 * boardLength - 5,
  11 * boardLength - 9,
  12 * boardLength + 2,
  13 * boardLength - 3,
  14 * boardLength + 8,
  15 * boardLength - 9,
  16 * boardLength + 1,
  16 * boardLength + 6,
  17 * boardLength - 7,
  17 * boardLength - 2,
  17 * boardLength + 2,
  18 * boardLength - 3,
];
export const tripleLetter = [
  2 * boardLength + 9,
  3 * boardLength + 5,
  4 * boardLength - 6,
  5 * boardLength + 3,
  6 * boardLength - 4,
  6 * boardLength + 9,
  9 * boardLength + 2,
  9 * boardLength + 6,
  10 * boardLength - 7,
  10 * boardLength - 3,
  12 * boardLength + 9,
  13 * boardLength + 3,
  14 * boardLength - 4,
  15 * boardLength + 5,
  16 * boardLength - 6,
  16 * boardLength + 9,
];
